openapi: 3.0.3
info:
  title: API сервиса otus-social-network-api
  version: 1.0.1
servers:
  - url: http://localhost:8080
tags:
  - name: OtusSocialNetwork
    description: otus-social-network service API
paths:
  /login:
    post:
      tags:
        - OtusSocialNetwork
      summary: Аутентификация пользователя
      operationId: login
      description: Упрощенный процесс аутентификации путем передачи идентификатор пользователя и получения токена для дальнейшего прохождения авторизации
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  $ref: 'components.yaml#/components/schemas/UserId'
                password:
                  type: string
                  example: Секретная строка
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: e4d2e6b0-cde2-42c5-aac3-0b8316f21e58
        '400':
          description: Невалидные данные
        '404':
          description: Пользователь не найден
        '500':
          $ref: 'components.yaml#/components/responses/5xx'
        '503':
          $ref: 'components.yaml#/components/responses/5xx'
  /user/register:
    post:
      tags:
        - OtusSocialNetwork
      summary: Регистрация нового пользователя
      operationId: register
      description: Регистрация нового пользователя
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: Имя
                second_name:
                  type: string
                  example: Фамилия
                birthdate:
                  $ref: 'components.yaml#/components/schemas/BirthDate'
                biography:
                  type: string
                  example: Хобби, интересы и т.п.
                city:
                  type: string
                  example: Москва
                password:
                  type: string
                  example: Секретная строка
      responses:
        '200':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    example: e4d2e6b0-cde2-42c5-aac3-0b8316f21e58
        '400':
          description: Невалидные данные
        '500':
          $ref: 'components.yaml#/components/responses/5xx'
        '503':
          $ref: 'components.yaml#/components/responses/5xx'
  /user/get/{id}:
    get:
      tags:
        - OtusSocialNetwork
      summary: Получение анкеты пользователя
      operationId: getUser
      description: Получение анкеты пользователя
      parameters:
        - name: id
          schema:
            $ref: 'components.yaml#/components/schemas/UserId'
          required: true
          in: path
          description: Идентификатор пользователя
      responses:
        '200':
          description: Успешное получение анкеты пользователя
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/User'
        '400':
          description: Невалидные данные
        '404':
          description: Анкета не найдена
        '500':
          $ref: 'components.yaml#/components/responses/5xx'
        '503':
          $ref: 'components.yaml#/components/responses/5xx'